### ISSUE TITLE
Edge Chromium not updating

### ISSUE THREAD

**Issue by dennyamarojr** [simeononsecurity/Applocker-Hardening#1]
**Describe the bug**
After importing the applocker settings, Microsoft Edge Chromium are not updating. See screenshot below

**To Reproduce**

**Expected behavior**
I expect to be able update edge chromium, I check in other browsers like brave, vivaldi and it's working. I don't know which file is required by edge chromium, I try to see on google but didn't anything. I check in the event viewer and it seems the edge update service is not starting.

**Screenshots**
![image](https://user-images.githubusercontent.com/36896116/100753801-1d572880-339f-11eb-9639-38fe44173934.png)
![image](https://user-images.githubusercontent.com/36896116/100754107-8179ec80-339f-11eb-8e60-0faa9a1415ff.png)
![image](https://user-images.githubusercontent.com/36896116/100754148-8dfe4500-339f-11eb-880d-3926266c709f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2[e.g. iOS]
 - Browser Edge Chromium [e.g. chrome, safari]
 - Version 87.0.664.52 (Official build) (64-bit) [e.g. 22]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by simeononsecurity** [comment]
@dennyamarojr 

After reproducing the steps taken, we don't seem to be coming to the same conclusion.

![image](https://user-images.githubusercontent.com/4913771/100771666-4dfd8900-33c4-11eb-9e6e-c6e41fdda50a.png)

Please try to download the latest edge by visiting https://www.microsoft.com/en-us/edge
To reinstall it manually and try again.

**Comment by dennyamarojr** [comment]
I will try to reinstall manually here

**Comment by dennyamarojr** [comment]
I reinstall Edge Chromium Dev here and it seems to have the same issue :( 
![image](https://user-images.githubusercontent.com/36896116/100778838-61a4f180-33bc-11eb-954d-c30e39c06e6c.png)

I don't know what exactly is the cause, when I remove the Applocker settings just works for me. Could this to be related to Exploit protection settings?

**Comment by dennyamarojr** [comment]
![image](https://user-images.githubusercontent.com/36896116/100779109-bea0a780-33bc-11eb-8a19-a3315cc4d51a.png)

and this is my program settings: https://we.tl/t-HKDpUWOB89

**Comment by dennyamarojr** [comment]
I will try to install Windows 10 in VM and them import the applocker to see if I can get the same message

**Comment by dennyamarojr** [comment]
I also will upload the Windows Defender settings, that may cause this issue (not sure).

![image](https://user-images.githubusercontent.com/36896116/100779585-733ac900-33bd-11eb-9a93-56d874a89c91.png)
![image](https://user-images.githubusercontent.com/36896116/100779611-80f04e80-33bd-11eb-9fad-0d7cee8faab6.png)
![image](https://user-images.githubusercontent.com/36896116/100779664-8f3e6a80-33bd-11eb-82b1-6096c8231f43.png)
![image](https://user-images.githubusercontent.com/36896116/100779764-b301b080-33bd-11eb-83c8-56fea595147d.png)
![image](https://user-images.githubusercontent.com/36896116/100779792-bdbc4580-33bd-11eb-9c69-3ba2a00e3d38.png)
![image](https://user-images.githubusercontent.com/36896116/100779825-c90f7100-33bd-11eb-9246-044eadc22396.png)
![image](https://user-images.githubusercontent.com/36896116/100779853-d593c980-33bd-11eb-95c3-05b35a548334.png)

**Comment by simeononsecurity** [comment]
We personally run all these settings locally.
The Applocker-Hardening is for more advanced users, who we don't expect to be running ie, edge, or chromium edge.
There is a reason we haven't implemented these settings under our more "turn-key" hardening scripts.
Though, we don't want this to be an expected behavior of our [Applocker-Hardening](https://github.com/simeononsecurity/Applocker-Hardening) script. 

We don't beleive this is an issue with Windows Defender or Windows Defender Application Control.
Chromium Edge is a Microsoft-signed binary and it shouldn't be blocked by Defender, even with our rules.

You can look in event viewer to see specifically if that service is being blocked by app locker.
You'll have to identify the binary associated with the stopped service and use [this documentation](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/monitor-application-usage-with-applocker#bkmk-applkr-view-log) to identify where to look in event viewer.

**Comment by dennyamarojr** [comment]
I check on google and it seems some problem with Windows itself, I import the Applocker settings and try to update manually with the .msi file from www.microsoftedge.com (link provided by you @simeononsecurity ) and it works. The process was made in a VM, I will try the same in my computer now and back here to answer and close this little issue. :) 
![image](https://user-images.githubusercontent.com/36896116/100801286-a3459480-33dc-11eb-91b8-308597f8ff77.png)
![image](https://user-images.githubusercontent.com/36896116/100801408-ce2fe880-33dc-11eb-9157-94a4cdd64d2f.png)

**Comment by dennyamarojr** [comment]
After sometimes trying the settings, find the solution. The problem with the Control Flow Guard in the exploit protection>program settings

I put the msedge.exe process and enable the Control flow guard (CFG)
and them enable Use strict CFG which cause the issue to preventing the browser check the updates here's the pic of the option enable
![image](https://user-images.githubusercontent.com/36896116/100812325-997a5c00-33f1-11eb-8834-5ff8a66a2cc8.png)

**Comment by simeononsecurity** [comment]
Interesting. 🤔 
Since this isn't relevant to this repo we'll have to close it.

That setting is quite possibly a part of [Windows-Optimize-Harden-Debloat](https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat) or [Windows-Defender-Hardening](https://github.com/simeononsecurity/Windows-Defender-Hardening) if you also ran them.

But, @dennyamarojr let me suggest that you don't just run any of my scripts without reading the "suggested reading" sections and the readme. With all things security, things are likely to break when you force them to be secure. Also, it's not smart to just run any script on the internet.  Slow down and try to take some time to understand them.

Furthermore, if you're interested in security, you shouldn't be using any of the Microsoft browsers or any Chrome variant.
Install FireFox and take a look at [Recommended Browser Plugins](https://simeononsecurity.ch/recommendations/browser_plugins/) and my [FireFox-Privacy-Script](https://github.com/simeononsecurity/FireFox-Privacy-Script).
